valid eclipse home is set + attempt to get value from user.properties

diff --git a/bin/classpath b/bin/classpath
--- a/bin/classpath
+++ b/bin/classpath
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright (C) 2005 - 2009  Eric Van Dewoestine
+# Copyright (C) 2005 - 2010  Eric Van Dewoestine
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,6 +23,20 @@
 ECLIM_DIR=`dirname $0`
 ECLIM_DIR=`cd $ECLIM_DIR/.. && pwd`
 
+if [ -z "$ECLIPSE_HOME" ] ; then
+  ECLIPSE_HOME=`grep "eclipse\.home=" user.properties | cut -d '=' -f2`
+fi
+
+if [ -z "$ECLIPSE_HOME" ] ; then
+  echo "ECLIPSE_HOME not set."
+  exit 1
+fi
+
+if [ ! -d "$ECLIPSE_HOME/plugins" ] ; then
+  echo "Plugins directory not found in ECLIPSE_HOME: $ECLIPSE_HOME"
+  exit 1
+fi
+
 PLUGINS=`
   grep "path=\"ECLIPSE_HOME" $ECLIM_DIR/.classpath | \
   sed "s|.*path=\"ECLIPSE_HOME/.*[/]\?plugins/\([^_]*\)_.*|\1|"
@@ -30,7 +44,7 @@ PLUGINS=`
 
 for PLUGIN in $PLUGINS ; do
   PLUGIN_LOC=`
-    cd $ECLIM_ECLIPSE_HOME ;
+    cd $ECLIPSE_HOME ;
     find {dropins/*/eclipse/,}plugins -maxdepth 1 -name "${PLUGIN}_*"
   `
   sed -i "s|ECLIPSE_HOME/.*/${PLUGIN}_.[^\"]*|ECLIPSE_HOME/${PLUGIN_LOC}|" \
