update eclimd to use JAVA_HOME or JAVA env vars
on startup, echo the java path to use along with its version
information.

diff --git a/org.eclim/bin/eclimd b/org.eclim/bin/eclimd
--- a/org.eclim/bin/eclimd
+++ b/org.eclim/bin/eclimd
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright (C) 2005 - 2013  Eric Van Dewoestine
+# Copyright (C) 2005 - 2014  Eric Van Dewoestine
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -241,9 +241,30 @@ ARGS=(
   -application org.eclim.application
 )
 
+if [ -z "$JAVA" ] ; then
+  JAVA=$(which java 2> /dev/null)
+  if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/bin/java" ] ; then
+      JAVA="$JAVA_HOME/bin/java"
+    elif [ -x "$JAVA_HOME/jre/bin/java" ] ; then
+      JAVA="$JAVA_HOME/jre/bin/java"
+    fi
+  fi
+fi
+
+if [ -z "$JAVA" ] ; then
+  echo "Unable to locate your java install."
+  echo "Please set your JAVA_HOME environment variable or"
+  echo "set JAVA to the location of your java executable."
+  exit 1
+fi
+
 if [ $BACKGROUND -eq 1 ]; then
-  CLASSPATH="" java "${ARGS[@]}" > /dev/null &
+  CLASSPATH="" $JAVA "${ARGS[@]}" > /dev/null &
 else
-  echo java "${ARGS[@]}"
-  CLASSPATH="" java "${ARGS[@]}"
+  echo $JAVA -version
+  $JAVA -version
+  echo ""
+  echo $JAVA "${ARGS[@]}"
+  CLASSPATH="" $JAVA "${ARGS[@]}"
 fi
